// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"

/** Identifier type for public.app */
export type AppId = string & { __brand: "public.app" }

/** Represents the table public.app */
export default interface AppTable {
	id: ColumnType<AppId, AppId | undefined, AppId>

	public_hostname: ColumnType<string, string, string>
}

export type App = Selectable<AppTable>

export type NewApp = Insertable<AppTable>

export type AppUpdate = Updateable<AppTable>
