// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { AppId } from "./App"

/** Identifier type for public.app_connection_assignment */
export type AppConnectionAssignmentUserId = string & {
	__brand: "public.app_connection_assignment"
}

/** Identifier type for public.app_connection_assignment */
export type AppConnectionAssignmentSlug = string & {
	__brand: "public.app_connection_assignment"
}

/** Represents the table public.app_connection_assignment */
export default interface AppConnectionAssignmentTable {
	app_id: ColumnType<AppId, AppId, AppId>

	user_id: ColumnType<
		AppConnectionAssignmentUserId,
		AppConnectionAssignmentUserId,
		AppConnectionAssignmentUserId
	>

	slug: ColumnType<
		AppConnectionAssignmentSlug,
		AppConnectionAssignmentSlug,
		AppConnectionAssignmentSlug
	>

	connection_id: ColumnType<string, string, string>
}

export type AppConnectionAssignment = Selectable<AppConnectionAssignmentTable>

export type NewAppConnectionAssignment = Insertable<AppConnectionAssignmentTable>

export type AppConnectionAssignmentUpdate = Updateable<AppConnectionAssignmentTable>
