// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { AppId } from "./App"
import type { AppUserUserId } from "./AppUser"

/** Identifier type for public.app_folder */
export type AppFolderId = string & { __brand: "public.app_folder" }

/** Represents the table public.app_folder */
export default interface AppFolderTable {
	id: ColumnType<AppFolderId, AppFolderId | undefined, AppFolderId>

	app_id: ColumnType<AppId, AppId, AppId>

	user_id: ColumnType<AppUserUserId | null, AppUserUserId | null, AppUserUserId | null>

	slug: ColumnType<string, string, string>
}

export type AppFolder = Selectable<AppFolderTable>

export type NewAppFolder = Insertable<AppFolderTable>

export type AppFolderUpdate = Updateable<AppFolderTable>
