// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely"
import type { AppId } from "./App"

/** Identifier type for public.app_user */
export type AppUserUserId = string & { __brand: "public.app_user" }

/** Represents the table public.app_user */
export default interface AppUserTable {
	app_id: ColumnType<AppId, AppId, AppId>

	user_id: ColumnType<AppUserUserId, AppUserUserId, AppUserUserId>
}

export type AppUser = Selectable<AppUserTable>

export type NewAppUser = Insertable<AppUserTable>

export type AppUserUpdate = Updateable<AppUserTable>
